export const ADD_LOG_DIALOG = 'ADD_LOG_DIALOG';
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_DIALOG_WITH_ARGS = 'OPEN_DIALOG_WITH_ARGS';
export const CREATE_USER_DIALOG = 'CREATE_USER_DIALOG';
export const DECRYPT_DIALOG = 'DECRYPT_DIALOG';